# Generated by Django 5.0 on 2024-04-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateurs', '0005_remove_prestataire_employeur_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='nfcTag',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='qrTag',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
