# Generated by Django 5.0 on 2024-05-01 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateurs', '0006_utilisateur_nfctag_utilisateur_qrtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='symboles_cibles',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
