# Generated by Django 5.0 on 2024-05-05 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateurs', '0007_utilisateur_symboles_cibles'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='cni',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
