# Generated by Django 5.0 on 2024-01-06 08:17

import datetime
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_utilisateurs', '0002_utilisateur_remove_prestataire_user_delete_agent_and_more'),
        ('gestions_formations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='formation',
            name='modules',
        ),
        migrations.AddField(
            model_name='formation',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='formation',
            name='date_fin',
            field=models.DateField(default=datetime.datetime(2024, 4, 5, 8, 17, 4, 845096, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='formation',
            name='prestataires',
            field=models.ManyToManyField(blank=True, related_name='formations', to='gestion_utilisateurs.utilisateur'),
        ),
        migrations.AddField(
            model_name='formation',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='module',
            name='date_debut',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='module',
            name='date_fin',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='formateur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='gestion_utilisateurs.utilisateur'),
        ),
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('adresse', models.CharField(blank=True, max_length=200, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='Logo')),
                ('utilisateurs', models.ManyToManyField(blank=True, related_name='entreprises', to='gestion_utilisateurs.utilisateur')),
            ],
            options={
                'verbose_name': 'Entreprise',
                'verbose_name_plural': 'Entreprises',
            },
        ),
    ]
