# Generated by Django 5.0 on 2024-01-10 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestions_formations', '0002_remove_formation_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='date_fin',
            field=models.DateField(default=datetime.datetime(2024, 4, 9, 12, 12, 24, 564099, tzinfo=datetime.timezone.utc)),
        ),
    ]
