# Generated by Django 5.0 on 2024-04-02 19:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestions_formations', '0009_remove_entreprise_adresse_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='symboles_cibles',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='formation',
            name='validite',
            field=models.DateField(default=datetime.datetime(2025, 4, 2, 19, 14, 14, 399399, tzinfo=datetime.timezone.utc)),
        ),
    ]
