# Generated by Django 5.0 on 2024-04-02 19:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestions_formations', '0010_alter_formation_symboles_cibles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='validite',
            field=models.DateField(default=datetime.datetime(2025, 4, 2, 19, 23, 35, 915147, tzinfo=datetime.timezone.utc)),
        ),
    ]
