# Generated by Django 5.0 on 2024-04-18 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestions_formations', '0011_alter_formation_validite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='validite',
            field=models.DateField(default=datetime.datetime(2025, 4, 18, 9, 46, 5, 113888, tzinfo=datetime.timezone.utc)),
        ),
    ]
