# Generated by Django 5.0 on 2024-04-24 08:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestions_formations', '0012_alter_formation_validite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='validite',
            field=models.DateField(default=datetime.datetime(2025, 4, 24, 8, 39, 33, 244349, tzinfo=datetime.timezone.utc)),
        ),
    ]
