# Generated by Django 5.0 on 2024-04-24 10:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestions_formations', '0014_alter_formation_validite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='validite',
            field=models.DateField(default=datetime.datetime(2025, 4, 24, 10, 45, 6, 704476, tzinfo=datetime.timezone.utc)),
        ),
    ]
