# Generated by Django 5.0 on 2024-05-05 15:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestions_formations', '0016_remove_formation_symboles_cibles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='validite',
            field=models.DateField(default=datetime.datetime(2027, 5, 6, 15, 26, 11, 941788, tzinfo=datetime.timezone.utc)),
        ),
    ]
